### ISSUE TITLE
docker-compose build && docker-compose up is throwing error

### ISSUE THREAD

**Issue by abhaybharti** [delta-reporter/delta-reporter#23]
I am trying to deploy delta-reporter on Windows 10 docker. It is failing with error -

My env -
OS : Windows 10
Python : 3.9.4

WARNING: The HOME variable is not set. Defaulting to a blank string.
db uses an image, skipping
redis uses an image, skipping
rabbit uses an image, skipping
Building delta_core
[+] Building 5.1s (10/15)
 => [internal] load build definition from Dockerfile                                                                                                                                                          0.0s
 => => transferring dockerfile: 32B                                                                                                                                                                           0.0s
 => [internal] load .dockerignore                                                                                                                                                                             0.0s
 => => transferring context: 2B                                                                                                                                                                               0.0s
 => [internal] load metadata for docker.io/library/python:3.7-alpine                                                                                                                                          2.1s
 => [internal] load build context                                                                                                                                                                             0.1s
 => => transferring context: 3.89kB                                                                                                                                                                           0.0s
 => CACHED [base 1/1] FROM docker.io/library/python:3.7-alpine@sha256:56cb9e22b1ab2264251c111144f22a2bc83d2404ca30bf4237178f49703ebbb8                                                                        0.0s
 => CACHED [builder 1/5] RUN mkdir /install                                                                                                                                                                   0.0s
 => CACHED [builder 2/5] RUN apk update && apk add postgresql-dev gcc musl-dev                                                                                                                                0.0s
 => CACHED [builder 3/5] WORKDIR /install                                                                                                                                                                     0.0s
 => CACHED [builder 4/5] COPY requirements.txt /requirements.txt                                                                                                                                              0.0s
 => ERROR [builder 5/5] RUN pip install --install-option="--prefix=/install" -r /requirements.txt                                                                                                             2.8s
------
 > [builder 5/5] RUN pip install --install-option="--prefix=/install" -r /requirements.txt:
#10 2.363 /usr/local/lib/python3.7/site-packages/pip/_internal/commands/install.py:232: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
#10 2.363   cmdoptions.check_install_build_global(options)
#10 2.363 ERROR: Location-changing options found in --install-option: ['--prefix'] from command line. This is unsupported, use pip-level options like --user, --prefix, --root, and --target instead.
------
executor failed running [/bin/sh -c pip install --install-option="--prefix=/install" -r /requirements.txt]: exit code: 1
ERROR: Service 'delta_core' failed to build : Build failed

**Comment by Jnegrier** [comment]
Hey @abhaybharti 

Thanks a million for bringing this to our attention, I'm really sorry that it took us so long to see the issue.

The project is still quite green, so we expect to reply faster as we continue to improve our processes.

This issue got fixed on this PR: https://github.com/delta-reporter/delta-core/pull/66

Kind regards
